
#
# this will make the backend (google) lie about its content type.
# obviously, search results are not json.
#

backend: https://google.com

add_headers:
  content-type: application/json

remove_headers:
  content-type: true


#
# some general service configs
#

middleware:
  - request_identification
  - request_tracing
  - route_metrics

log:
  console:
    level: info


